name: Build
description: Build application with Maven and create a new Docker image
inputs:
  dockerfile_path:
    description: "Path to the Dockerfile"
    required: false
    default: "src/main/docker/Dockerfile.jvm"
  image_name:
    description: "Image name"
    default: "academy"
  tag_name:
    description: "Tag name"
    default: "$(date +%s)"
  docker_username:
    description: Docker username
    default: ""
  docker_token:
    description: Docker docker
    default: ""
  docker_repository:
    description: Repository name
    default: "dilantaskin721/academy"
runs:
  using: composite
  steps:
    - run: |
        echo "Update me with the necessary steps to build the application"
      shell: bash
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_token }}
    - name: Push the image to Docker GitHub
      shell: bash
      run: docker tag ${{ inputs.image_name}}:${{ inputs.tag_name}} ${{ inputs.docker_repository }}:${{ inputs.image_name}}
